name: xcube-viewer workflow

on:
  push:
  release:
    types: [published]

env:
  APP_NAME: xcube-viewer
  ORG_NAME: bcdev
  REG_NAME: quay.io
  UNITTEST: 0

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup xcube-viewer
        if: ${{ env.UNITTEST == '1' }}
        run: |
          yarn install
      - name: unittest-xcube-viewer
        if: ${{ env.UNITTEST == '1' }}
        run: |
          yarn test
      - uses: codecov/codecov-action@v1
        with:
          verbose: true # optional (default = false)
  # build docker images and push to
  build-docker-image:
    runs-on: ubuntu-latest
    name: build-docker-image
    needs: unittest
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - name: get-release-tag
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: info
        id: info
        run: |
          echo "TAG: ${{ steps.release.outputs.tag }}"
          echo "EVENT: ${{ github.event_name }}"
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build-push-docker-image-latest
        if: ${{ github.event_name == 'push' && steps.release.outputs.tag == 'master'  }}
        with:
          image: ${{ env.ORG_NAME }}/${{ env.APP_NAME }}
          tags: master, latest
          registry: ${{ env.REG_NAME }}
          username: ${{ secrets.QUAY_REG_USERNAME }}
          password: ${{ secrets.QUAY_REG_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build-push-docker-image-release
        if: ${{ github.event_name == 'release' }}
        with:
          image: ${{ env.ORG_NAME }}/${{ env.APP_NAME }}
          tags: ${{ steps.release.outputs.tag }}
          registry: ${{ env.REG_NAME }}
          username: ${{ secrets.QUAY_REG_USERNAME }}
          password: ${{ secrets.QUAY_REG_PASSWORD }}
  update-version-xcube-version:
    env:
      PUSH: 1
    runs-on: ubuntu-latest
    needs: build-docker-image
    name: update-viewer-hub-tag
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: bc-org/k8s-configs
          ref: 'dzelge_xxx_xcube-viewer'
          delimiter: ' '
          token: ${{ secrets.XCUBE_GITHUB_K8S_CONFIGS_PAT }}
          path: k8s
      - name: get-release-tag
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: deployment-phase
        id: deployment-phase
        uses: bc-org/gha-determine-phase@v0.1
        with:
          event_name: ${{ github.event_name }}
          tag: ${{ steps.release.outputs.tag }}
      - name: get-hash
        id: get-hash
        run: |
          HASH=$(skopeo inspect docker://${{ env.REG_NAME }}/${{ env.ORG_NAME }}/${{ env.APP_NAME }}:${{ steps.release.outputs.tag }} | jq '.Digest')
          if [[ "$HASH" == *"sha256"* ]]; then
            echo ::set-output name=hash::$HASH
          else
            echo "No has present. Using none as hash. This will use the version tag instead for deployment."
            echo ::set-output name=hash::none
          fi
      - name: info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Deployment Stage: ${{ steps.deployment-phase.outputs.phase }}"
          echo "Release Tag: ${{ steps.release.outputs.tag }}"
          echo "Deployment Release Tag: ${{ steps.deployment-phase.outputs.tag }}"
          echo "Deployment Digest: ${{ steps.get-hash.outputs.hash }}"
      - name: set-version-tag-xcube-viewer
        uses: bc-org/gha-update-application-version-tags@main
        with:
          app: xcube-viewer
          phase: 'dev' #${{ steps.deployment-phase.outputs.phase }}
          tag: 'tt' #${{ steps.deployment-phase.outputs.tag }}
          hash: 'sha256asöoivjsadöoijv' #${{ steps.get-hash.outputs.hash }}
          working-directory: ./k8s/xcube-viewer-app/helm
      - name: cat-result
        working-directory: ./k8s/xcube-viewer-app/helm
        run: |
          head values-dev.yaml
#          head values-stage.yaml
#          head values-prod.yaml
      - name: Pushes to another repository
        if: ${{ steps.deployment-phase.outputs.phase != 'ignore' }}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.XCUBE_GITHUB_K8S_CONFIGS_PAT }}
        with:
          source-directory: 'k8s'
          destination-github-username: 'bc-org'
          destination-repository-name: 'k8s-configs'
          user-email: bcdev@brockmann-consult.de
          target-branch: main
          commit-message: ${{ github.event.release }}. Set version to ${{ steps.release.outputs.tag }}
